#!/bin/bash

hq=0
odir=../../gamedata/textures


for i in `seq 1 5`; do
    eval "render$i=0"
done

while [ $# -ne 0 ]; do
    case "$1" in
	-hq)
	    hq=1
	    ;;
	-all)
	    for i in `seq 1 5`; do
		eval "render$i=1"
	    done
	    ;;
	-D)
	    shift
	    odir=$1
	    ;;
	-r?)
            echo "render${1#-r}=1"
	    eval "render${1#-r}=1"
	    ;;
	
    esac
    shift
done

siz=256
if [ $hq == 1 ]; then
    siz=512
fi

for i in `seq 1 5`; do
    if eval "test \$render$i -eq 1"; then
	povray +W$siz +H$siz +A0.4 +KFF6 +KC sky$i.pov +O$odir/sky$i.png +FN
    fi
done